const ORDER_STATUS = {
  PENDING_PAYMENT: 0,
  PAID: 1,
  PENDING_COMPLETE: 2,
  COMPLETED: 3,
  CANCELED: 4
};

const CODE = {
  SUCCESS: 200,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  SERVER_ERROR: 500
};

module.exports = { ORDER_STATUS, CODE };
